<!DOCTYPE html>
<html>
<head>
	<title>General Tab</title>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<link href="../../../content.css" rel="stylesheet" type="text/css"/>
</head>
<body>
	<div class="Heading2">Use custom Makefile</div>
	<div class="Text">By default, Dev-C++ constructs its own makefile based on the configuration on the previous tabs. Here you can point Dev to a custom replacement. Dev-C++ will not generate any more makefiles if this option is used.</div>
	<br/>
	<div class="Heading2">Information about customizing the makefile...</div>
	<div class="Text">Click!</div>
	<br/>
	<div class="Heading2">Include the following files into the makefile</div>
	<div class="Text">If your custom makefile (or Dev's one) is getting so large that it can't be properly maintained in a single file anymore, you can then include files here.</div>
</body>
</html>